using System;
using System.Collections.Generic;

namespace CommSights_Api.Database.ModelCommSights
{
    public partial class ProductProperty
    {
        public int Id { get; set; }
        public int? UserCreated { get; set; }
        public DateTime? DateCreated { get; set; }
        public int? UserUpdated { get; set; }
        public DateTime? DateUpdated { get; set; }
        public int? ParentId { get; set; }
        public string? Note { get; set; }
        public bool? Active { get; set; }
        public int? Source { get; set; }
        public string? Day { get; set; }
        public string? Week { get; set; }
        public string? Month { get; set; }
        public string? Quarter { get; set; }
        public string? Year { get; set; }
        public int? ArticleTypeId { get; set; }
        public int? CategoryMainId { get; set; }
        public string? CategoryMain { get; set; }
        public int? CategorySubId { get; set; }
        public string? CategorySub { get; set; }
        public int? CompanyId { get; set; }
        public string? CompanyName { get; set; }
        public int? CorpCopyId { get; set; }
        public string? CorpCopy { get; set; }
        public decimal? Soecompany { get; set; }
        public int? FeatureCorpId { get; set; }
        public string? FeatureCorp { get; set; }
        public int? AssessId { get; set; }
        public int? SegmentId { get; set; }
        public string? Segment { get; set; }
        public int? ProductId { get; set; }
        public string? ProductNameProjectName { get; set; }
        public int? SegmentProductId { get; set; }
        public string? SegmentProduct { get; set; }
        public decimal? Soeproduct { get; set; }
        public int? FeatureProductId { get; set; }
        public string? FeatureProduct { get; set; }
        public int? IndustryId { get; set; }
        public string? Industry { get; set; }
        public string? Guicode { get; set; }
        public string? Code { get; set; }
        public decimal? Point { get; set; }
        public int? KeywordCount { get; set; }
        public bool? IsSummary { get; set; }
        public bool? IsData { get; set; }
        public bool? IsDaily { get; set; }
        public bool? IsWeekly { get; set; }
        public bool? IsMonthly { get; set; }
        public bool? IsQuarterly { get; set; }
        public bool? IsYearly { get; set; }
        public decimal? RomeCorpVnd { get; set; }
        public decimal? RomeCorpUsd { get; set; }
        public decimal? RomeProductVnd { get; set; }
        public decimal? RomeProductUsd { get; set; }
        public int? TierCommsightsId { get; set; }
        public string? TierCommsights { get; set; }
        public int? TierCustomerId { get; set; }
        public string? TierCustomer { get; set; }
        public string? SpokePersonName { get; set; }
        public string? SpokePersonTitle { get; set; }
        public decimal? SpokePersonValue { get; set; }
        public decimal? ToneValue { get; set; }
        public decimal? HeadlineValue { get; set; }
        public decimal? FeatureValue { get; set; }
        public decimal? TierValue { get; set; }
        public decimal? PictureValue { get; set; }
        public decimal? Mps { get; set; }
        public int? SentimentCorpId { get; set; }
        public string? SentimentCorp { get; set; }
        public int? SentimentProductId { get; set; }
        public string? SentimentProduct { get; set; }
        public int? ReportMonthlyId { get; set; }
        public string? Headline { get; set; }
        public string? Url { get; set; }
        public string? Page { get; set; }
        public string? Journalist { get; set; }
        public string? HeadlineEngLish { get; set; }
        public string? MediaTitle { get; set; }
        public string? MediaType { get; set; }
        public string? Duration { get; set; }
        public decimal? Advalue { get; set; }
        public DateTime? DatePublish { get; set; }
        public string? FileName { get; set; }
        public decimal? SentimentValue { get; set; }
        public string? CampaignName { get; set; }
        public string? KeyMessage { get; set; }
        public decimal? CompetitiveNewsValue { get; set; }
        public string? CompetitiveWhat { get; set; }
        public decimal? Kolvalue { get; set; }
        public decimal? OtherValue { get; set; }
        public decimal? TasteValue { get; set; }
        public decimal? PriceValue { get; set; }
        public decimal? NutritionFactValue { get; set; }
        public decimal? VitaminValue { get; set; }
        public decimal? GoodForHealthValue { get; set; }
        public decimal? BottleCanDesignValue { get; set; }
        public bool? IsCoding { get; set; }
        public bool? IsAnalysis { get; set; }
        public bool? IsDownload { get; set; }
        public bool? IsSend { get; set; }
        public string? CampaignKeyMessage { get; set; }
        public DateTime? DateCoding { get; set; }
        public DateTime? DateAnalysis { get; set; }
        public bool? IsCopy { get; set; }
        public int? CopyVersion { get; set; }
        public int? SourceProperty { get; set; }
        public bool? IsDailyDownload { get; set; }
        public DateTime? DateDailyDownload { get; set; }
        public string? FullName { get; set; }
        public int? MembershipId { get; set; }
        public string? SourceCode { get; set; }
        public string? TitleProperty { get; set; }
        public string? IssueNumber { get; set; }
        public DateTime? DateReport { get; set; }
        public string? Location { get; set; }
        public string? ProductFeature { get; set; }
    }
}
